### ISSUE TITLE
json pretty print enhancement

### ISSUE THREAD

**Issue by cjp256** [QtMark/qmjson#11]
+1 for the last line getting a proper line ending.

**Comment by rianquinn** [comment]
is this for toJson() or toJsonFile()? Currently toJsonFile already adds a "\r\n".

**Comment by cjp256** [comment]
toJson().  \r\n seems os dependent... is it possible to just use \n and allow the user to write to file accordingly if they need to reformat?  (and add last newline?) :)

**Comment by rianquinn** [comment]
Oh... hahahaha, you want unix encoding instead of Windows, yeah we can do that.
